### ISSUE TITLE
use Pyinstaller to compile your python code to executable

### ISSUE THREAD

**Issue by Rajx05** [HYDRAWOLFY/Arithmetic-Suite#1]
[https://www.geeksforgeeks.org/convert-python-script-to-exe-file/](url) 
check this guide for help @HYDRAWOLFY

**Comment by HYDRAWOLFY** [comment]
Thank  You so much :))

**Comment by HYDRAWOLFY** [comment]
I added this to my to-do list on github readme illl proceed with it as soon as i integrate some stuff
